# Use C++test 2020.2 Standard
name: CI-Test-2020-Standard

on:
#  push:
#    branches: [main]

  workflow_dispatch:


jobs:
  test-cpptest:
    name: Analyze project with C/C++test
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Generate BDF
      env:
        CPPTEST_SCAN_PROJECT_NAME: FlowAnalysis
      run: |
        & "C:\cpptest\2020.2_standard\cpptest\bin\cpptesttrace.exe" make all
      working-directory: ./FlowAnalysis
      
#    - name: Generate Local Settings
#      run: |
#        echo report.format=sarif > ls_st.properties
#        echo scontrol.git.exec=git.exe >> ls_st.properties
#        echo scontrol.rep.git.branch=main >> ls_st.properties
#        echo scontrol.rep.git.workspace=C:\\actions-runner\\_work\\github-actions-cpptest\\github-actions-cpptest >> ls_st.properties
#        echo scontrol.rep.git.url=https://github.com/cpptest-techmatrix/github-actions-cpptest >> ls_st.properties

    - name: Run C++test
      # Use the 'run-cpptest-action' GitHub Action.
      uses: parasoft/run-cpptest-action@1.0.1
      with:
        installDir: 'C:\cpptest\2020.2_standard\cpptest'
        compilerConfig: 'gcc_7-64'
        testConfig: 'builtin://MISRA C 2012'
        input: './FlowAnalysis/cpptestscan.bdf'
        reportFormat: xml,html,custom
        additionalParams: '-property report.custom.extension=sarif -property report.custom.xsl.file=${PARASOFT_SARIF_XSL}'
#        commandLinePattern : ' ${cpptestcli} -data ../workspace -config "${testConfig}" -report "${reportDir}" -bdf "${input}" ${additionalParams} '

    # Uploads analysis results in the SARIF format, so that they are displayed as GitHub code scanning alerts.
    - name: Upload results (SARIF)
      if: always()
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: reports/report.sarif
    
    # Uploads an archive that includes all report files (.xml, .html, .sarif).
    - name: Archive reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Static analysis reports
        path: reports/*.*
